name: Tech Tumbleweeds
url: https://drautb.github.io
paginate: 10
baseurl: /
destination: ./_site
highlighter: pygments
future: true
permalink: /:year/:month/:day/:title/
excerpt_separator: <!--more-->
