name: Ben Draut
url: https://drautb.github.io
paginate: 1
paginate_path: "/blog/page:num/"
baseurl: /
destination: ./_site
highlighter: rouge
future: true
permalink: /:year/:month/:day/:title/
excerpt_separator: <!--more-->
plugins: [jekyll-paginate]
