baseurl:     /
destination: ./_site
plugins:     ./_plugins
pygments:    true
future:      true
permalink:   date
markdown:    redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
excerpt_separator: <!--more-->
